'''
process data before LSTM classification
'''

def lstm_process(data):
    target_names_0 = ["ENFJ","ENFP","ENTJ","ENTP","ESFJ","ESFP","ESTJ","ESTP","INFJ","INFP","INTJ","INTP","ISFJ","ISFP","ISTJ","ISTP"]
    #Dataset for 7 Classes
    data_7c = data.copy()
    data_7c.type.replace("ISTP","Other", inplace=True)
    data_7c.type.replace("ISFP","Other", inplace=True)
    data_7c.type.replace("ISTJ","Other", inplace=True)
    data_7c.type.replace("ISFJ","Other", inplace=True)
    data_7c.type.replace("ENTJ","Other", inplace=True)
    data_7c.type.replace("ENFJ","Other", inplace=True)
    data_7c.type.replace("ESTP","Other", inplace=True)
    data_7c.type.replace("ESFP","Other", inplace=True)
    data_7c.type.replace("ESFJ","Other", inplace=True)
    data_7c.type.replace("ESTJ","Other", inplace=True)
    target_names_1 = ['ENFP','ENTP','INFJ','INFP','INTJ','INTP','Other']
    #Dataset for Extraversion vs Introversion
    data_EI = data.copy()
    data_EI.type.replace("INFP","Introversion", inplace=True)
    data_EI.type.replace("INFJ","Introversion", inplace=True)
    data_EI.type.replace("INTP","Introversion", inplace=True)
    data_EI.type.replace("INTJ","Introversion", inplace=True)
    data_EI.type.replace("ISTP","Introversion", inplace=True)
    data_EI.type.replace("ISFP","Introversion", inplace=True)
    data_EI.type.replace("ISTJ","Introversion", inplace=True)
    data_EI.type.replace("ISFJ","Introversion", inplace=True)
    data_EI.type.replace("ENTP","Extraversion", inplace=True)
    data_EI.type.replace("ENFP","Extraversion", inplace=True)
    data_EI.type.replace("ENTJ","Extraversion", inplace=True)
    data_EI.type.replace("ENFJ","Extraversion", inplace=True)
    data_EI.type.replace("ESTP","Extraversion", inplace=True)
    data_EI.type.replace("ESFP","Extraversion", inplace=True)
    data_EI.type.replace("ESFJ","Extraversion", inplace=True)
    data_EI.type.replace("ESTJ","Extraversion", inplace=True)
    target_names_2 = ['Extraversion', 'Introversion']
    #Dataset for Intuition vs Sensing
    data_SI = data.copy()
    data_SI.type.replace("INFP","Intuition", inplace=True)
    data_SI.type.replace("INFJ","Intuition", inplace=True)
    data_SI.type.replace("INTP","Intuition", inplace=True)
    data_SI.type.replace("INTJ","Intuition", inplace=True)
    data_SI.type.replace("ISTP","Sensing", inplace=True)
    data_SI.type.replace("ISFP","Sensing", inplace=True)
    data_SI.type.replace("ISTJ","Sensing", inplace=True)
    data_SI.type.replace("ISFJ","Sensing", inplace=True)
    data_SI.type.replace("ENTP","Intuition", inplace=True)
    data_SI.type.replace("ENFP","Intuition", inplace=True)
    data_SI.type.replace("ENTJ","Intuition", inplace=True)
    data_SI.type.replace("ENFJ","Intuition", inplace=True)
    data_SI.type.replace("ESTP","Sensing", inplace=True)
    data_SI.type.replace("ESFP","Sensing", inplace=True)
    data_SI.type.replace("ESFJ","Sensing", inplace=True)
    data_SI.type.replace("ESTJ","Sensing", inplace=True)
    target_names_3 = ['Intuition', 'Sensing']
    #Dataset for Feeling vs Thinking
    data_TF = data.copy()
    data_TF.type.replace("INFP","Feeling", inplace=True)
    data_TF.type.replace("INFJ","Feeling", inplace=True)
    data_TF.type.replace("INTP","Thinking", inplace=True)
    data_TF.type.replace("INTJ","Thinking", inplace=True)
    data_TF.type.replace("ISTP","Thinking", inplace=True)
    data_TF.type.replace("ISFP","Feeling", inplace=True)
    data_TF.type.replace("ISTJ","Thinking", inplace=True)
    data_TF.type.replace("ISFJ","Feeling", inplace=True)
    data_TF.type.replace("ENTP","Thinking", inplace=True)
    data_TF.type.replace("ENFP","Feeling", inplace=True)
    data_TF.type.replace("ENTJ","Thinking", inplace=True)
    data_TF.type.replace("ENFJ","Feeling", inplace=True)
    data_TF.type.replace("ESTP","Thinking", inplace=True)
    data_TF.type.replace("ESFP","Feeling", inplace=True)
    data_TF.type.replace("ESFJ","Feeling", inplace=True)
    data_TF.type.replace("ESTJ","Thinking", inplace=True)
    target_names_4 = ['Feeling', 'Thinking']
    #Dataset for Perceiving vs Judging
    data_JP = data.copy()
    data_JP.type.replace("INFP","Perceiving", inplace=True)
    data_JP.type.replace("INFJ","Judging", inplace=True)
    data_JP.type.replace("INTP","Perceiving", inplace=True)
    data_JP.type.replace("INTJ","Judging", inplace=True)
    data_JP.type.replace("ISTP","Perceiving", inplace=True)
    data_JP.type.replace("ISFP","Perceiving", inplace=True)
    data_JP.type.replace("ISTJ","Judging", inplace=True)
    data_JP.type.replace("ISFJ","Judging", inplace=True)
    data_JP.type.replace("ENTP","Perceiving", inplace=True)
    data_JP.type.replace("ENFP","Perceiving", inplace=True)
    data_JP.type.replace("ENTJ","Judging", inplace=True)
    data_JP.type.replace("ENFJ","Judging", inplace=True)
    data_JP.type.replace("ESTP","Perceiving", inplace=True)
    data_JP.type.replace("ESFP","Perceiving", inplace=True)
    data_JP.type.replace("ESFJ","Judging", inplace=True)
    data_JP.type.replace("ESTJ","Judging", inplace=True)
    target_names_5 = ['Judging', 'Perceiving']
    return data_7c,data_EI,data_JP,data_SI,data_TF,target_names_0,target_names_1,target_names_2,target_names_3,target_names_4,target_names_5